name: Deploy to neocities

# only run on changes to master
on:
  push:
    branches:
      - main 

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: v18.0.0
    - name: Install deps and build
      run: |
        npm ci
        npm run build
    # When the dist_dir is ready, deploy it to neocities
    - name: Deploy to neocities
      id: deploy
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_KEY }}
        cleanup: true 
        dist_dir: dist 

    - name: Deploy to Neocities fallback
      if: ${{ steps.deploy.outcome == 'failure' && github.ref == 'refs/heads/main' }}
      uses: jonchang/deploy-neocities@master
      with:
        key: ${{ secrets.NEOCITIES_API_KEY }}
        dir: dist 
        clean: true
